server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.142.10.47:6033/ianhau?serverTimezone=GMT%2b8
    username: root
    password: 123456
  data:
    mongodb:
      uri: mongodb://43.142.10.47:14444/data_center

mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl